### ISSUE TITLE
How can you exit shapes.native properly? (and not use 100% CPU)

### ISSUE THREAD

**Issue by edwintorok** [realworldocaml/book#2269]
How can you exit shapes.native properly? If I just close the window then a process stays behind that uses 100% CPU. I had to use either Ctrl-C or kill but that is not a very nice way ... would be nice if some callback could be invoked when the user closes the window that would exit the application properly.

**Comment by yminsky** [comment]
I think we're going to replace Async_graphics entirely, so I don't think we're going to solve this particular issue.
