### ISSUE TITLE
Bug in installation instructions? 

### ISSUE THREAD

**Issue by vmanis** [realworldocaml/book#2494]
I'm not sure whether this is a bug in the software, or in the installation instructions. When I followed them on Ubuntu 13.10 (building OCaml and OPAM both from source, as specified in the instructions), I attempted to do `opam install core utop'; the log output indicated that the installation failed, citing an undefined record field, pmod_attributes. I have a transcript, but I'm not attaching it to this initial report, in case this is a well-known problem.

I suspect this issue I've just created should be closed, but if you could indicate in the close message where I should report it, that would be useful. I would also suggest that the installation document should include a Troubleshooting section with pointers to where to go if some step or other fails.

**Comment by yminsky** [comment]
Closing, since I think the above is probably more of an issue for opam-level documentation.
