### ISSUE TITLE
Install on Ubuntu server 14.04

### ISSUE THREAD

**Issue by audionuma** [realworldocaml/book#2604]
label : page-installation
Hello,
about https://github.com/realworldocaml/book/wiki/Installation-Instructions
It might be worth to mention in the install guide that the

```
$ opam install core utop
```

installation fails on on Ubuntu 14.04 server guest with 512 MB RAM allocated because of RAM missing.
Raising the RAM allocated to 1 GB solve the issue (see https://github.com/ocaml/opam-repository/issues/2203).
Thanks.

**Comment by yminsky** [comment]
This is not the right place for general installation failure problems.
