### ISSUE TITLE
Comments not viewable on website

### ISSUE THREAD

**Issue by rrshaban** [realworldocaml/book#2675]
Or, at least, there seems to be no indication that there are comments -- maybe I'm misunderstanding the intention of the system? Every link at the end of a paragraph shows up for me as "0 comments" -- even after paragraphs that I have posted on. I have tried refreshing, but still every link says 0 comments, and clicking the link results in a submission form. Are comments not meant to be viewable by readers? I thought it was something more like this:

 ![example of commenting at the end of paragraphs](http://premium.wpmudev.org/blog/wp-content/uploads/2014/02/paracom-count.png)

 Or, at least, that could be nice! 

[picture source](http://premium.wpmudev.org/blog/how-to-have-paragraph-commenting-just-like-medium/)

**Comment by avsm** [comment]
A GitHub API change broke it -- will be fixed shortly.

**Comment by NathanReb** [comment]
I'm closing this as it refers to v1, same as #2763.
