### ISSUE TITLE
New comment on block [block-idm181612718960]

### ISSUE THREAD

**Issue by cgopalan** [realworldocaml/book#2706]
Instead of :
"For this chapter, we've picked the OCaml library by Martin Jambon."
It should be:
"For this chapter, we've picked the Yojson library by Martin Jambon."

The link is correct but the text is wrong.

**Comment by avsm** [comment]
This is fixed in the development version of Real World OCaml, available at https://dev.realworldocaml.org.  Thanks for the report!
