### ISSUE TITLE
New comment on block [block-idm181610693312]

### ISSUE THREAD

**Issue by arjunravinarayan** [realworldocaml/book#2710]
you need to do "opam install ctypes-foreign", and not just "opam install ctypes" (ctypes-foreign will install ctypes as a dependency) otherwise you get errors. See https://github.com/ocamllabs/ocaml-ctypes/issues/290

**Comment by bendiken** [comment]
Thanks. I just stumbled onto this, myself, and executing `opam install ctypes-foreign` indeed fixes it.

For the benefit of people googling the problem, the error message in `utop` when doing `#require "ctypes.foreign";;`, per the instructions in the book, is as follows:

    No such package: ctypes.foreign.threaded - required by `ctypes.foreign'

**Comment by avsm** [comment]
This is fixed in the development version of Real World OCaml, available at https://dev.realworldocaml.org.  Thanks for the report!
