### ISSUE TITLE
New comment on block [block-idm181620794896]

### ISSUE THREAD

**Issue by pimiento** [realworldocaml/book#2733]
I've got an error:

utop # let log_entry maybe_time message =
    let time =
      match maybe_time with
      | Some x -> x
      | None -> Time.now ()
    in
    Time.to_sec_string time ^ " -- " ^ message
  ;;
Error: This expression has type zone:Core.Zone.t -> string                                                                                                                                            but an expression was expected of type string

**Comment by avsm** [comment]
This is fixed in the development version of Real World OCaml, available at https://dev.realworldocaml.org.  Thanks for the report!
