### ISSUE TITLE
inconsistent installation instructions for setting up utop

### ISSUE THREAD

**Issue by barkmadley** [realworldocaml/book#2749]
Just letting you know about this issue a new user was having after reading the installation instructions on this repositories wiki:

https://github.com/realworldocaml/book/wiki/Installation-Instructions#setting-up-and-using-utop

When you reach this section, you add these lines of setup to your .ocamlinit file. However there appear to be two things wrong with this picture:
1. ppx_jane should technically only be available for OCaml 4.02.3, however the previous section (https://github.com/realworldocaml/book/wiki/Installation-Instructions#configuring-opam) tells the user to setup OCaml 4.01.0
2. ppx_jane provides PPX extensions, whereas the rest of the book references camlp4 syntax extensions.

New user posted for help on reddit here: https://www.reddit.com/r/ocaml/comments/4j6fig/core_syntax_extensions/

**Comment by NathanReb** [comment]
I'm closing this as it is quite out of date and I believe utop installation instructions have been fixed since then!
