### ISSUE TITLE
New comment on block [block-idm181621356784]

### ISSUE THREAD

**Issue by matthiasgoergens** [realworldocaml/book#2750]
Aren't C++ templates more ad-hoc?  (Anyway, I guess your formulation is precise enough for a one line intro.)

**Comment by avsm** [comment]
Indeed, a one line intro won't dive into this. But if you're really interested, then https://www.cs.bham.ac.uk/~hxt/2016/c-plus-plus/templates-slides.pdf is a nice overview.
