### ISSUE TITLE
New comment on block [block-idm181612009760]

### ISSUE THREAD

**Issue by jmikkola** [realworldocaml/book#2770]
Running the command  listed below in a cloned copy of the examples repository results in the following error (using Ocaml 4.03.0):

```
Solver failed:
  Ocamlbuild cannot find or build test.ml.  A file with such a name would usually be a source file.  I suspect you have given a wrong target name to Ocamlbuild.
```

_edit_: It turns out the command needs to be run in the parsing-test/ directory rather than the parsing/ directory. This is unclear when reading the book.

**Comment by avsm** [comment]
Thanks; we've ported v2 of the book to dune, so running the examples should be less manual by the time we release it.
