### ISSUE TITLE
New comment on block [block-idm181617964368]

### ISSUE THREAD

**Issue by khaledez** [realworldocaml/book#2784]
List.map example didn't work with OCaml 4.04.1 ..
This is what I got:
# List.map ~f:basic_color_to_int [Blue;Red];;
Error: The function applied to this argument has type 'a list -> 'b list
This argument cannot be applied with label ~f

To fix it:
# List.map basic_color_to_int [Blue;Red];;

**Comment by yminsky** [comment]
The dev version should be more up to date with current libraries.
