### ISSUE TITLE
New comment on block [block-idm181621257968]

### ISSUE THREAD

**Issue by MiBengtsson** [realworldocaml/book#2797]
I have OCaml 4.04.1, and then it seems that just "open Core.Std;;" won't work: `unbound module Core`. 
What did work for me was to run 
```
#require "core";;
open Core;;
```
It even told me that Core.Std was deprecated, and Core was sufficient.

**Comment by yminsky** [comment]
This is now reflected in the new book at dev.realworldocaml.org
