### ISSUE TITLE
New comment on block [block-idm181621257968]

### ISSUE THREAD

**Issue by kaaloo** [realworldocaml/book#2801]
I see the following message from utop using OCaml 4.05.0:

utop # open Core.Std;;
Characters 5-13:                                                                                            Warning 3: deprecated: module Core.Std                                                                      [since 2017-02] Use Core. The Std sub-module is no longer needed

**Comment by agarwal** [comment]
This warning is correct. In the latest versions of Core, you should do `open Core`.
