### ISSUE TITLE
Feedback button is in the way

### ISSUE THREAD

**Issue by ramn** [realworldocaml/book#2803]
When reading the web book on mobile, the Feedback button in the right margin is quite annoying and in the way. Could we please get rid of it, at least on mobile?

**Comment by yminsky** [comment]
@SanderSpies, what do you think?

**Comment by NathanReb** [comment]
Gave this a quick look and I believe it has been fixed as the feedback button is quite thin on mobile and doesn't overlap on the book content!

Please feel free to re-open if you feel otherwise!
