### ISSUE TITLE
Error "utop was built without camlp4 support"

### ISSUE THREAD

**Issue by tobia** [realworldocaml/book#2804]
The [installation instructions](https://dev.realworldocaml.org/install.html) recommend adding this line to `.ocamlinit`:

    #camlp4o;;

But, at least on my system (Ubuntu 16.04 with system compiler 4.02.3) I get the following error:

    utop was built without camlp4 support.                                          

If I understand correctly, CamlP4 has been phased out for PPX.

But how do we get PPX working in Utop?

**Comment by MarcusE1W** [comment]
Same here for Archlinux ..

**Comment by tobia** [comment]
The problem is that the installation instructions give no clue on how to get things like `[@@deriving fields]`, `[@@deriving sexp]`, and `[%sexp_of: ...]` to work in Utop.

I tried dozens of different directives, before finding this simple combination of magic words:

	#require "ppx_sexp_conv";;
	#require "ppx_fields_conv";;
	open Core.Std;;

This is my `~/.ocamlinit` so far, in case others find it useful:

	let () =
	  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
	  with Not_found -> ()
	;;
	#use "topfind";;
	#thread;;

	(* Less annoying Utop prompt *)

	#require "react";;
	#require "lambda-term";;
	open React;;
	open LTerm_text;;
	UTop.prompt := fst (React.S.create LTerm_text.(eval [
	  S "\n";
	  B_fg (LTerm_style.cyan);
	  S "# ";
	]));;

	(* Core *)

	#require "core.top";;
	#require "core.syntax";;
	open Core;;

	(* PPX *)

	#require "ppx_sexp_conv";;
	#require "ppx_fields_conv";;
	open Core.Std;;

**Comment by tobia** [comment]
Update. I got `let%bind` to work by loading this extension:

    #require "ppx_let";;

and crucially by adding a shell alias that executes `utop-full`:

    alias utop=utop-full

[See this bug report and discussion.](https://github.com/diml/utop/issues/213)

**Comment by avsm** [comment]
Thanks for the report; I've started to refresh the installation instructions as we've pulled up the development version to 4.06.0.  I'll take a look at the utop-full issue and see if we can fix it upstream... it's a bit tricky without also fixing compiler-libs first.

**Comment by NathanReb** [comment]
@avsm what's the status on this?

**Comment by avsm** [comment]
This has been fixed in the dev version; no more references to camlp4o

**Comment by avsm** [comment]
read this too fast -- we need to look into the use of utop-full _vs_ utop

**Comment by XVilka** [comment]
Camlp4 support was removed from utop. I think this can be closed now.

**Comment by yminsky** [comment]
Agreed.  Closing.
