### ISSUE TITLE
Chapter 8: Timings seem to be broken in snippets

### ISSUE THREAD

**Issue by mquirin** [realworldocaml/book#2806]
In the code snippets in [Chapter 8 (Dev version)](https://dev.realworldocaml.org/08-imperative-programming.html) the `time` function is used on multiple occasions, however the snippets show an error instead of the timings:
`Error: Unbound value time`

This seems to be connected to the first error message in this Chapter:
```
# #require "mtime.os.top";;
No such package: mtime.os.top
```

**Comment by NathanReb** [comment]
I'm closing this as there is no such require statement in the book now.

Note that you should probably use `mtime.top` instead!

Please feel free to re-open if the issue persists somehow!
