### ISSUE TITLE
Why is an error expected here?

### ISSUE THREAD

**Issue by jnavila** [realworldocaml/book#2807]
https://github.com/realworldocaml/book/blob/029aa114a971cc3320faaf29558cdc7527a0564d/examples/code/variants/blang.topscript#L71-L74

Is this really intended? The described error message does not fit with the flow of surrounding text.

**Comment by christophe-riolo** [comment]
No error intended but List.mem needs a fuction to say how to test equality; the correct code should be : 
```ocaml
let and_ l =
  if List.mem l (Const false) ~equal:(=) then Const false
  else
    match List.filter l ~f:((<>) (Const true)) with
    | [] -> Const true
    | [ x ] -> x
    | l -> And l
;;
```
I'm also reading and found this weird — I guess the return values are computed automatically. So I tested how to correct it and came to submit the same issue :)

**Comment by jnavila** [comment]
Well. This would really require a PR to fix all the occurences where it's no longer applying.
