### ISSUE TITLE
Feeback button (online view) broken

### ISSUE THREAD

**Issue by skaller** [realworldocaml/book#2808]
Links don't work.

**Comment by dijkstracula** [comment]
Likewise.  More precisely, the GH link (https://github.com/realworldocaml/Real-World-OCaml) seems to point to an out of date location for realworldocaml/book and 404s, and the discussion iframe (https://discuss.ocaml.org/embed/comments?topic_id=583 , from a quick inspection) only contains an "Error Embedding" message.

**Comment by samoht** [comment]
Superseded by #2905
