### ISSUE TITLE
Layout hard to read

### ISSUE THREAD

**Issue by skaller** [realworldocaml/book#2809]
The online layout is almost unreadable. The fonts are too large and the line spacing way too large. The contents column is not movable and scales proportionally to the width of the browser defeating any attempt to get enough text on the screen to actually read. The right hand margin is way too large. 

Code examples which require scrolling are no good either. [Argg .. and opan can't install utop because lwt is broken]

**Comment by NathanReb** [comment]
I'm closing as I think the style has changed since then. Please feel free to re-open if you feel like RWO still is unreadable!
