### ISSUE TITLE
install.html: inconsistent OCaml version number

### ISSUE THREAD

**Issue by dijkstracula** [realworldocaml/book#2810]
Dear Real World OCaml authors,

As of ef2fb7c ,`install.html` still occasionally refers to OCaml version 4.01.0 even though the top-level section says to use 4.04.1.  In particular, readers are still instructed to run `opam switch 4.01.0`, so they would (if my understanding's correct) have to install `jbuilder` manually.

Thank you for a very useful first edition, and good luck with the revision!

Nathan

**Comment by avsm** [comment]
fixed in 8d1f56c60303524c1ac758a9460d8a17996072cc, thanks! (the online version will be updated shortly; just had a big tooling fix)
