### ISSUE TITLE
Outdated example in the section 13, Map and Hashtable

### ISSUE THREAD

**Issue by Succo** [realworldocaml/book#2813]
Hi

It seems example about creating map based on a Comparator are outdated.

```
Characters 57-71:
Error: The function applied to this argument has type
         ('a * 'b) list -> ('a, 'b, 'c) Map.t
This argument cannot be applied with label ~comparator
```

Is the error as seen in the generated book https://dev.realworldocaml.org/13-maps-and-hashtables.html

Not sure if I should raise the issue here or in the example repo since I believe this https://github.com/realworldocaml/examples/blob/master/code/maps-and-hash-tables/main.topscript the actual code.

**Comment by NathanReb** [comment]
Closing this as it referes to outdated content. Please feel free to re-open if the latest version still contain any such bug!
