### ISSUE TITLE
Explain the current status of backtraces in OCaml

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#2846]
The language here is out of date for Base, at least:

![image](https://user-images.githubusercontent.com/715302/35482333-82d1b944-0401-11e8-8e7d-ea68e816e4a4.png)

I'd prefer to fix this once I can get examples really running again, which will be doable soon as the new way of writing shell fragments lands.

**Comment by NathanReb** [comment]
We should probably take a look at this as I believe the tooling issues are fixed now! cc @yminsky

**Comment by NathanReb** [comment]
Actually this probably has been fixed already!
