### ISSUE TITLE
HTML generation is messed up

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#2907]
A few examples from what's currently up on dev.realworldocaml.org

![selection_001](https://user-images.githubusercontent.com/715302/37744957-7d8a4fda-2d48-11e8-940c-f6bb296fd35e.png)
![selection_002](https://user-images.githubusercontent.com/715302/37744959-817ea00a-2d48-11e8-9a70-3412b988d3d9.png)

This seems like a recent regression.

**Comment by samoht** [comment]
This is probably introduced by #2897 I need to check why entities are not resolved properly with lambdasoup.

**Comment by samoht** [comment]
This is now fixed; #2910 will fix the other issue where words are being a bit shuffled...
