### ISSUE TITLE
Have one file per chapter

### ISSUE THREAD

**Issue by samoht** [realworldocaml/book#2972]
We want to move towards a more literate programming style, where the chapter will mix text and code. Currently, the text is in markdown (pandoc flavor) with the `<link>` elements pointing to external  ocaml-topexepct scripts (`.mlt`) and cram-style shell scripts (`.sh` and `.errsh`).

We want to have only one `.mlt` file, which will include mardown and shell sections.

**Comment by yminsky** [comment]
I'm pretty sure this is now done.
