### ISSUE TITLE
How to view and create comments per paragraph in each chapter?

### ISSUE THREAD

**Issue by RogerTarani** [realworldocaml/book#2981]
I'm/we are currently reading dev RWO and I'm reporting (to myself) possible errors in the text or in the OCaml code examples. I feel like tested code examples, Base/Core_Kernel/Core libs libs and jbuilder altogether have improved the user experience (at least in the 4 first chapters, compared to the _tags system used when RWO version 1 was released).

- **Where can I view existing comments in the context of a paragraph?**
- **Where can I write comments in order to help the authors to improve this book, elsewhere than in the realworldocaml/book weird and inappropriate place?** (in the first RWO, there was a bunch of errors which interrupted a lot the study of the book, but side comments about them were a little bit helpful or reassuring).

I think that reading the book and using the code examples smoothly and with no interruption is definitely a must have feature in this book for new comers or come-backers.    

Thanks for your feedback.
And thanks a lot for your impressive work.

**Comment by NathanReb** [comment]
We're currently working on it and haven't added a proper commenting system for the dev version yet.

See #2973!

I believe in the meantime opening issues on this repo is the way to go if you want to provide feedback on the dev version content.

I'm closing this but feel free to re-open if you have further questions!
