### ISSUE TITLE
V2 of "install.html" - trying to install cohttp via opam install cohttp & throws error 

### ISSUE THREAD

**Issue by jamestromano** [realworldocaml/book#2984]
I'm a newbie to ocaml.  I was following the installation of ocaml using opam
I've switched/installed to version 4.06.1
When I get to the opam install cohttp I see this error:
The following dependencies couldn't be met:
- ppx_type_conv -> ppxlib < 0.3.0
Your request can't be satisfied:
- No package matches ppxlib<0.3.0

Not sure if I have to switch back to an earlier version of ocaml?  I tried this under 4.05.0 too and it throws the same error.

I'm runnig this on CentOS 7, via a Window 10 Hyper-V

**Comment by yminsky** [comment]
This is probably a better question for discuss.ocaml.org.

https://discuss.ocaml.org/c/learning

That said, this stuff should all work for OCaml 4.06, and I'm currently
running all this on 4.06.1 without any problems. You certainly shouldn't
need to downgrade.

**Comment by jamestromano** [comment]
Thank you for the response.
I installed the latest version of Debian and had no issues with the initial
installation.

Thanks,
Jim

**Comment by j-m-hoffmann** [comment]
I have a the same problem, on ubuntu18.04 with ocaml 4.06.1:
opam install cohttp -y
gives:
Sorry, no solution found: there seems to be a problem with your request.
No solution found, exiting

**Comment by j-m-hoffmann** [comment]
I got a response on https://discuss.ocaml.org
The aspcud package needs to be installed via apt.

**Comment by avsm** [comment]
Closing this, as opam2 includes a solver that avoids the need for aspcud
