### ISSUE TITLE
V2 of Real World Ocaml misspelled the power of Float to "**."

### ISSUE THREAD

**Issue by Tiancheng-Luo** [realworldocaml/book#2986]
V2 of guided-tour -> Tuples  

```Ocaml
let distance (x1,y1) (x2,y2) =
  Float.sqrt ((x1 -. x2) **. 2. +. (y1 -. y2) **. 2.)
;;
val distance : float * float -> float * float -> float = <fun>
```
```The **. operator used above is for raising a floating-point number to a power.  ```

The power of Float should be `**` rather than `**.`, at least in versions prior to 4.06 as I know of.

**Comment by yminsky** [comment]
This is not a mistake. This was changed in Base to be more consistent with the rest of the floating point operators.
