### ISSUE TITLE
aarch64 install problem on Debian/aml-s905x-cc

### ISSUE THREAD

**Issue by KenDickey** [realworldocaml/book#2994]
Greetings,

I am a noob and would like to go through your great introductory exposition, but am having problems installing Core.

Can you help me out?

Thanks much,
-KenD

[core-prob.txt](https://github.com/realworldocaml/book/files/2408269/core-prob.txt)

**Comment by yminsky** [comment]
Closing.  This isn't really the right place for distro-specific installation problems.  Better to raise issues on the specific library that isn't installing properly.
