### ISSUE TITLE
Text and code don't match

### ISSUE THREAD

**Issue by VasilyFomin** [realworldocaml/book#3000]
Hi,
Thanks for working on the book, so far it's been great!

Just wanted to report a small issue I found in the [Files, Modules, and Programs](http://dev.realworldocaml.org/files-modules-and-programs.html):

> This uses ocamlfind, a tool which itself invokes other parts of the OCaml toolchain (in this case, ocamlc) with the appropriate flags to link in particular libraries and packages. Here, -package base is asking ocamlfind to link in the Base library; -linkpkg asks ocamlfind to link in the packages as is necessary for building an executable, while **-thread** turns on threading support, which is required for Base.  

The text above mentions that we need to link against `thread` library, but it seems to link without it and the source example also doesn't have it.

**Comment by yminsky** [comment]
Resolved here:

https://github.com/realworldocaml/book/pull/3009

 (In the future, a PR for such simple fixes is always welcome!)
