### ISSUE TITLE
Extra backtick in Variants chapter causes bad formatting

### ISSUE THREAD

**Issue by emannes** [realworldocaml/book#3012]
![image](https://user-images.githubusercontent.com/3751025/46600874-8e4d6f00-cab9-11e8-9d54-5f5362805140.png)

See https://github.com/realworldocaml/book/commit/88f10c2e4d1b3b0240724ceabdbb8084913a6c80?diff=unified#r30808970

**Comment by NathanReb** [comment]
This has been fixed!
