### ISSUE TITLE
Extra underscore in First-Class Modules

### ISSUE THREAD

**Issue by emannes** [realworldocaml/book#3013]
> In addition, we use the `ppx_sexp_conv` syntax extension which interprets the
`[@@deriving_sexp]` annotation. When `ppx_sexp_conv` sees `[@@deriving sexp]`
attached to a signature, it replaces it with declarations of s-expression
converters, for example:[sexp declaration]{.idx}

`[@@deriving_sexp]` should read `[@@deriving sexp]`.

**Comment by yminsky** [comment]
Thanks again! Fixed.
