### ISSUE TITLE
[404 Not Found] https://realworldocaml.org/install

### ISSUE THREAD

**Issue by yvan-sraka** [realworldocaml/book#3019]
https://realworldocaml.org/install

**Comment by yvan-sraka** [comment]
Yes that is not the link given on top of https://v1.realworldocaml.org/ page 😕!

**Comment by amireldor** [comment]
The installation instructions here: http://dev.realworldocaml.org/prologue.html#installation-instructions leads to a 404 (it's without the .html suffix).
