### ISSUE TITLE
Rendering of record syntax is broken

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3027]
You can see it at the top of this page.

https://dev.realworldocaml.org/records

The source block looks like this:

```
type <record-name> =
    { <field> : <type>;
      <field> : <type>;
      ...
    }
```
and I imagine what's going on is that the angle-brackets are being rendered as bogus html

**Comment by deisner** [comment]
This problem appears to occur throughout the book. Here's another example: 

https://dev.realworldocaml.org/files-modules-and-programs.html

This is the source:

`val <identifier> : <type>`

And this is how it's rendered:

![image](https://user-images.githubusercontent.com/742277/48962923-2d3d0600-ef56-11e8-9d67-d45049471e40.png)

**Comment by yminsky** [comment]
Though the online book isn't yet fixed. Problem with the deploy script?

**Comment by samoht** [comment]
I need to update the docker image to use latest mdx, doing that now.
