### ISSUE TITLE
Typo in section on Polymorphic variants

### ISSUE THREAD

**Issue by retnuh** [realworldocaml/book#3049]
Hi there, I'm reading through the section on polymorphic Variants.

It's discussing the whole `Grey` vs `Gray` thing.  The first code example looks like this:

```
[...]

let extended_color_to_int = function
  | `RGBA (r,g,b,a) -> 256 + a + b * 6 + g * 36 + r * 216
  | `Grey x -> 2000 + x
  | (`Basic _ | `RGB _ | `Gray _) as color -> color_to_int color
```

And it goes on to discuss how an explicit type annotation would help:

```
let extended_color_to_int : extended_color -> int = function
  | `RGBA (r,g,b,a) -> 256 + a + b * 6 + g * 36 + r * 216
  | `Gray x -> 2000 + x
  | (`Basic _ | `RGB _ | `Gray _) as color -> color_to_int color
```

But in the second example, there is no `Grey` tag - it's spelled (correctly) as `Gray`.

(Sorry I don't know how to quite the block number).

**Comment by XVilka** [comment]
Well, it is done on the purpose - note that book shows how compiler complains that `Grey` is unused exactly, so I guess it was the point of the example.

**Comment by retnuh** [comment]
I thought the example was showing something that would fail to compile, though?

**Comment by NathanReb** [comment]
Indeed I think in the second example it's a typo!

**Comment by yminsky** [comment]
Good point.  Fix in https://github.com/realworldocaml/book/pull/3184.
