### ISSUE TITLE
Text mentioning `jbuilder`, code using `dune`

### ISSUE THREAD

**Issue by blaiseli** [realworldocaml/book#3055]
Dear authors,

In the section about IO (https://dev.realworldocaml.org/imperative-programming.html#input-and-output), I noticed the following sentence:

> We can build this program using `jbuilder` and run it.

This is followed by code not using `jbuilder`, but `dune` instead.

If I understand correctly, `dune` is just a renamed version of `jbuilder`, so maybe all occurrences of `jbuilder` should be updated.

**Comment by XVilka** [comment]
You can just send a PR.
