### ISSUE TITLE
NESTING LETS WITH LET AND IN Section in Chapter 1 -- References log-entry

### ISSUE THREAD

**Issue by mclagett** [realworldocaml/book#3062]

**Comment by mclagett** [comment]
The section entitled NESTING LETS WITH LET AND IN in Chapter 1 starts out with "log_entry was our first use of let to define a new variable within the body of a function."  Problem is, no log_entry function has yet appeared in the text.

**Comment by NathanReb** [comment]
I believe this has been fixed! Closing!
