### ISSUE TITLE
It looks like your example formatter "eats" the `<fun>` that is part of utop's/toplevel's output

### ISSUE THREAD

**Issue by zhenya1007** [realworldocaml/book#3079]
It looks like your example formatter "eats" the `<fun>` that is part of utop's/toplevel's output.  For example, the type of `ratio` function, as printed by utop/toplevel ends up being shown as: 

```
val ratio : int -> int -> float = 
```

I am quite certain it is _actually_ printed as 

```
val ratio : int -> int -> float = <fun>
```

I am guessing your example formatter "thinks" that `<fun>` is an unknown HTML/XML tag, and "eats" it.

**Comment by avsm** [comment]
It looks like this might be a highlight.js issue, since the output html has `&lt;fun&gt;` which is then turned into `<fun></fun/>` after the highlighting pass.
