### ISSUE TITLE
Add the [@@deriving *] examples and information in Variants chapter

### ISSUE THREAD

**Issue by XVilka** [realworldocaml/book#3082]
Well, using derives helps a lot for a huge chunk of data processing logic, so I believe it is important
to document them in the book as a good practice:
- [ ] `[@@deriving enum]`
- [ ] `[@@deriving show]`
- [ ] `[@@deriving eq, ord, compare]`
- [ ] `[@@deriving json]`

Using deriving is quite common in other languages as well, for example Rust. In fact I saw deriving in most of the Rust codebases, and the attribute documented in their core guides:
- https://doc.rust-lang.org/reference/attributes/derive.html
- https://doc.rust-lang.org/rust-by-example/trait/derive.html

So documenting it in the RWO will benefit many projects (a lot of people are unaware of these extentsions).

**Comment by NathanReb** [comment]
This should and will be documented in the PPX chapter but it might be worth mentioning it in a couple other places indeed.

**Comment by yminsky** [comment]
Various derivers are referenced in the records chapter (fields), imperative programming (sexp, compare, hash), data-serialization and error-handling (sexp), maps-and-hashtables (compare), and testing (quickcheck).

I agree that it would be nice to add a PPX chapter that gave more of an overview of what was available, and there is some extra coverage to add (for example, ppx_typed_fields would be great for both records and variants), but I don't see variants as a hotspot for this issue.
