### ISSUE TITLE
Imperative Dictionary example does not compile

### ISSUE THREAD

**Issue by m-laniakea** [realworldocaml/book#3083]
[This](http://dev.realworldocaml.org/imperative-programming.html#example-imperative-dictionaries) is the section being referred to.

Because the example uses Base's `( = )` operator, which is an integer-only comparator,
it does not compile.

One solution would be to add the statement `open Base.Poly`.

**Comment by m-laniakea** [comment]
Fixed [here](https://github.com/realworldocaml/book/pull/3053). 
Live page was simply not updated.

**Comment by pablodcar** [comment]
@m-laniakea Is the live page going to be updated eventually whith the fixes?

**Comment by yminsky** [comment]
I believe the live page is now fixed.
