### ISSUE TITLE
Typo operator on section Record and variants

### ISSUE THREAD

**Issue by fahmiirsyadk** [realworldocaml/book#3134]
Hi, i found typo `**.` instead of `**` in section A Guided Tour ( Record and Variants ).

- `let magnitude { x = x_pos; y = y_pos } =
Float.sqrt (x_pos **. 2. +. y_pos **. 2.);;`
- `let magnitude { x; y } = Float.sqrt (x **. 2. +. y **. 2.);;`
- `let stdev rsum =
  Float.sqrt (rsum.sum_sq /. Float.of_int rsum.samples
-. (rsum.sum /. Float.of_int rsum.samples) **. 2.)
;;`

- The ` **. `  operator used above is for raising a floating-point number to a power.

according to the book that i've , its using `**` operator.

**Comment by NathanReb** [comment]
That's because the examples in the book have `Base` (see https://github.com/janestreet/base) opened.

`Base` exposes an int power operator `**` and a float power operator `**.`. 

Maybe we should emphasize that it overrides some operators from the OCaml stdlib a bit more.

**Comment by benjub** [comment]
> Maybe we should emphasize that it overrides some operators from the OCaml stdlib a bit more.

That would be great.
