### ISSUE TITLE
Type errors from dune builds are marked non-deterministic

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3137]
Here's an example from "Files, Modules and Programs":

```sh dir=../../examples/code/files-modules-and-programs/freq-cyclic1,non-deterministic=output
$ dune build freq.bc
      ocamlc .freq.eobjs/counter.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /Users/thomas/git/rwo/book/_opam/bin/ocamlc.opt -w -40 -g -bin-annot -I /Users/thomas/git/rwo/book/_opam/lib/base -I /Users/thomas/git/rwo/book/_opam/lib/base/caml -I /Users/thomas/git/rwo/book/_opam/lib/base/shadow_stdlib -I /Users/thomas/git/rwo/book/_opam/lib/sexplib -I /Users/thomas/git/rwo/book/_opam/lib/sexplib/0 -I /Users/thomas/git/rwo/book/_opam/lib/stdio -no-alias-deps -I .freq.eobjs -o .freq.eobjs/counter.cmo -c -impl counter.ml)
File "counter.ml", line 18, characters 18-31:
Error: Unbound module Counter
[1]
```

I imagine this is because the error captures a bunch of path information that varies depending on where things are run. I'm not sure how to fix this, but I think we have to, because it leaves too much of the book in a state where real errors in the text won't get caught.

Is there a dune flag we can use, maybe?

**Comment by yminsky** [comment]
I'm going to leave this open, but it's not a dune problem anymore, it appears.  One just has to fix these in the text. Assigning this to myself.

**Comment by avsm** [comment]
In this case, it's just the absolute build rule that is the problem isn't it? I wonder if we can just filter out stderr to not include that in the mdx output.  I've not checked to see if dune outputs all the errors on stderr, or just the verbose bits.

**Comment by yminsky** [comment]
Yup.  The build rule used to be spit out whenever there was an error, but it isn't anymore. The files-modules-and-programs chapter is now fixed up in master, just by running the previously non-deterministic or skipped tests.

Now, we just have to find the rest of them and give them the same treatment.  Now that I think about it, there's not much to do that's specific to this issue, so I'll just close it out.
