### ISSUE TITLE
Promotion runs in the wrong direction for non-toplevel code (and infinite promotion loops)

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3139]
Right now, promotion goes from the README file to the examples, which seems like the wrong direction.  Generally, one wants to go and fix ordinary OCaml code in the ordinary source file, since that's where you get proper feedback from the tools.

Also, there's some weird behavior where I sometimes see an infinite promotion loop, specifically when using parts and having spaces between the parts markers --- it can end up wanting to insert newlines endlessly.  Maybe changing the direction of promotion will fix this bug as well.

**Comment by avsm** [comment]
Agreed; I don't ever want to be editing OCaml code in a Markdown context.

**Comment by avsm** [comment]
Confirmed I'd like this changed as well. When editing #3140, I:

- changed the OCaml files in `examples/code/command-line-parsing/md5/md5.ml`
- ran `dune build --root examples/code/command-line-parsing/md5 md5.exe` to check they work
- ran `dune runtest book/command-line-parsing` -- and promotion happened in the wrong direction, and my changes in `examples/code/command-line-parsing/md5/md5.ml` were proposed to be overwritten by the version in the book.

**Comment by NathanReb** [comment]
Totally agree we're doing it the wrong way here.

I think that'll make even more sense once we moved the examples in the corresponding chapter's folder and make sure `runtest` actually build all examples that don't contain intentional errors.

I'll open a PR with that workflow for one chapter and we can discuss it further there!

**Comment by yminsky** [comment]
Can we make those changes independently? Certainly, I don't want to wait
for the disabled tests to be turned back on and fixed. This workflow really
makes getting those fixes in harder!

I don't nice waiting for the directory reorganization, as long as we do
that soon.

**Comment by NathanReb** [comment]
Yes of course! Also note that I plan to do that reorganization real soon anyway!
