### ISSUE TITLE
Provide a way to maintain the duniverse

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/book#3152]
Currently the duniverse is hard to maintain. `duniverse` is not released yet and the current master version doesn't provide a way to update to the latest opam versions or to easily install new repositories inside the `duniverse/`.

We need commands in duniverse to be able to do those things, editing the `dune-get` file by hand is not a long term solution.

**Comment by avsm** [comment]
Done now with `make duniverse-upgrade`
