### ISSUE TITLE
Typo in section Designing with Modules

### ISSUE THREAD

**Issue by barisere** [realworldocaml/book#3161]
In the section Designing with Modules, under [Design for the Call Site](https://github.com/realworldocaml/book/tree/master/book/files-modules-and-programs#design-for-the-call-site), the following typo appears in the last sentence of the fourth paragraph.
> A good rule of thumb is that names that have a small scope should be short, whereas names that have a large scope, like the name of a function **in an a module interface**, should be longer and more explicit.

The correct phrase should be either "in a module interface" or "in an interface".

**Comment by avsm** [comment]
fixed, thanks!
