### ISSUE TITLE
Promotions include stray whitespace

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3164]
Promotions for responses from the toplevel often including trailing whitespace, which is annoying because I have my editor set up to remove trailing whitespace on save, which causes spurious back-and-forth changes,  as show up here for example:

https://github.com/realworldocaml/book/pull/3162

Is this something we can fix?

**Comment by NathanReb** [comment]
I already reported in https://github.com/realworldocaml/mdx/issues/146.

This definitely sound like something we can fix, I'll take a look!

**Comment by clecat** [comment]
This problem should be solved by now

**Comment by NathanReb** [comment]
Yeah we'll have to update the embedded mdx though, I'll take care of that!

**Comment by yminsky** [comment]
Any progress on this?

**Comment by NathanReb** [comment]
Yeah sry, haven't had a lot of time to take care of that but we're working on rebasing the `mdx` fork we use on top of the latest master changes and trying to get rid of the hacks on the way! I'll focus on the rebasing part and updating our vendored `mdx`!
