### ISSUE TITLE
Changing the order of things in the TOC doesn't cause the TOC to be regenerated on the site

### ISSUE THREAD

**Issue by yminsky** [realworldocaml/book#3171]
I noticed this while working on the testing chapter.  Blowing away _build and recreating everything takes care of it, but there's probably a missing dependency somewhere.

**Comment by NathanReb** [comment]
@yminsky do you by any chance have a way to reproduce that? We changed the rules for this parts quite a lot recently so it might not be the case anymore.

I'll try to take a look myself. Just to make sure I got this right, the procedure would be:
1. `dune build @site/@pdf`
2. swap to chapters in the toc.scm file
3. rerun 1

**Comment by yminsky** [comment]
Yeah, if that works, I think you should close this issue. I'll reopen if I
hit it again.

y
