### ISSUE TITLE
Typo in the section "Iteration Functions" of the chapter "Imperative Programing"

### ISSUE THREAD

**Issue by barisere** [realworldocaml/book#3180]
[Link to section Iteration Functions](https://github.com/realworldocaml/book/tree/master/book/imperative-programming#iteration-functions). The first sentence of the second paragraph reads:
> Dlist has two such iterators: iter, the goal of which is to call a unit-producing function on every element of the list, in order; and find_el, which runs a provided test function on **each values** stored in the list, returning the first element that passes the test.

The correct grammar is "...which runs a provided test function on **each value**..."; singular "value" to match quantifier "each".

PS: I hope I'm not just being pedantic. Thanks for this book. It's the best introduction to OCaml I've seen.

**Comment by yminsky** [comment]
Thanks.  Fixed by https://github.com/realworldocaml/book/pull/3181.
