### ISSUE TITLE
The Y Combinator is hiding in "Memoization and Dynamic Programming"

### ISSUE THREAD

**Issue by barisere** [realworldocaml/book#3182]
While reading the section "Memoization and Dynamic Programming" (under Imperative Programming), I recognized the Y Combinator in the following definitions.
```ocaml
let fib_norec fib i =
  if i <= 1 then i
else fib (i - 1) + fib (i - 2)
;;

let make_rec f_norec =
  let rec f x = f_norec f x in
  f
;;

let fib = make_rec fib_norec
;;
```
The reason why it caught my attention is that recently I tried to read some material on the Y Combinator, but got I frustrated when I couldn't understand it. Seeing its form in a functional language made something tick. Then I went to [this article on Medium that explains the Y Combinator](https://medium.com/@ayanonagon/the-y-combinator-no-not-that-one-7268d8d9c46), and now I get it (my brain still hurts).
I think calling it out in a hint can enrich the book more. I like that it helped me understand the Y Combinator which I've been struggling with, and even practitioners can use a little detour into a rabbit hole (which is how I got here 🙂 ).

Edit: I hope I'm correct, but that construction really looks like the Y Combinator.

**Comment by yminsky** [comment]
It's a nice suggestion, but there's a lot to explain there already, and I'm leery of weighing the prose down more with another digression.

Thanks for the suggestion, though, and I'm glad you found the example enlightening!
