### ISSUE TITLE
No comment links in dev-page...

### ISSUE THREAD

**Issue by tbrup** [realworldocaml/book#3183]
I have worked through the first version and liked it.  Thanks for this introduction to Ocaml!  I actually quite like Ocaml now.

When I saw that the 2nd edition is in works, I wanted to contribute, but there seems to be no comment function (yet).  I tried three browsers (Safari, Firefox, Chrome) and could not see any comment link...

My main feedback as a user: dune is a disaster for starting with Ocaml! (I dislike dune for its insistence on enforcing Windows-limitations on all other OSs, but this is not the main issue).   I started learning Ocaml by solving the Euler-project tasks.  These are short exercises that can be solved in a single file, maybe two.  AFAICT, dune can only build a single executable per directory and fails if there is a syntax error in an unrelated file -- something that happens often when learning new languages.  Why should the build of 'problem155' from 'problem155.ml' fail if there is an error in 'problem175.ml'?

The corebuild method was simpler to learn and use for beginning with Ocaml.  Dune seems to have a much bigger scope and, for me, just gets in the way.  As a beginner, I am now not only struggling with Ocaml, but also with a build system and one that seems to be too OS specific.

I have no real solution, but feel the book loses from using dune.

**Comment by yminsky** [comment]
I recommend you give Dune another shot.  Any tool will have some growing pains, but Dune scales way better than ocamlbuild (which is what corebuild was based on) does.  FWIW, Dune's design doesn't come from Windows at all; it was based on Jenga, which is a Linux-only system.  People sometimes think it's Windows-based because it creates executables ending in .exe, but that turns out to be just a coincidence.

(It does have good Windows support, which is great, but that is a recent innovation.)

**Comment by tbrup** [comment]
Some time has gone by, and I feel like I can give some feedback.  This is just my experience and an attempt at giving feedback on the book.

The main reason why I actually write this comment is "Programming Elixir" by Dave Thomas that I am reading right now: chapter 13 does, in my opinion, a good job of showing how elixir's build system (mix) meshes with the whole elixir environment and how to build a simple application.  I wished I had a similar chapter on Ocaml.  Reading up on mix made me guess what dune tries to do, and it also gave me the trigger to try again some things (like building the small command line application consisting of multiple source files with Ocaml).  ... just to run into the same roadblocks with dune as before

I have been trying to understand dune, but find it still very unapproachable, to the point of being annoying.  Let's face it: as a reader trying to learn Ocaml, I would like to work through some examples, try out things (make small changes), fall on my face, figure out what is wrong with my changes, fix them and learn -- after all it is the little details that you have to get right and that will lead to real understanding.  The main focus should be on the language, not on the build system.  Right now, I find myself still struggling with dune and find the documentation really lacking. 

I trust that the people pushing dune have their reasons.  If it is such an important component to use Ocaml well (which I hope it isn't), then understanding the build system is key.  

I am sorry if this sounds like whining; I really like Ocaml, I have learnt a lot from reading the first edition of the book and was starting to think about using it for some smaller projects.  The investment into getting the build system to work is just not worth it for me as a hobbyist. 

Possibly this is really where the issue lies: it is not about Ocaml, it is more about the tools around Ocaml. There are quite a few stumbling stones for the novice to using Ocaml
- finding on-line documentation for e.g. "OCaml List" will point towards the standard library, you have to find out yourself that there are subtle changes if you're following the book.  V2 seems to make a better point about Base/Core though.
- why does "open Base" in utop give an error?  Ahh, I have forgotten an entry in .ocamlinit or it wasn't loaded because of an error
- dune...
- opam vs libraries in source directories (how do I build my own small library?)
- testing? version compatibilities? documentation of modules?...
So I guess my main feedback is: I would have profited a lot from a more rounded introduction (maybe in chapter 4 of V2) of the set of tools needed besides just the compiler.  A basic introduction into dune projects and how to use them, maybe some material on opam would go a long way.  

Anyhow, this is my feedback.  I will still try to use Ocaml, but find it increasingly frustrating.

**Comment by tbrup** [comment]
After my rant, I started to try to translate chapter 13 from "Programming Elixir" into Ocaml, just for the sake of learning dune.  You can find the result on https://github.com/tbrup/issues-ocaml.git
Maybe this helps better to understand the mundane issues that I ran into and maybe it helps someone else understanding the basics of dune.
