### ISSUE TITLE
Import HTML and LateX generation from mdx 

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/book#3213]
Currently we use `mdx output` command to generate the book HTML. What that command does is:
1. It strips the mdx specific labels from the markdown
2. Add custom styling to OCaml code blocks
3. Invoke pandoc with a specific set of options to generate our HTML

All this is very tightly tied to our needs and it would make more sense to import this code in the repo so we can iterate over it faster and remove it from `mdx` as it is unrelated to `mdx`'s role.

Since mdx exposes a public library we can start by importing the `mdx output` command code as is.

**Comment by XVilka** [comment]
Also related:
- [Issue - Add support for odoc](https://github.com/realworldocaml/mdx/issues/17)
- [Issue - Allowing support for Divs and Spans](https://github.com/ocaml/omd/issues/190)
- [Issue - Support for more `pandoc` extensions](https://github.com/ocaml/omd/issues/131)
- [Issue - Header identifiers](https://github.com/ocaml/omd/issues/146)
- [Issue - Handle extended markdown](https://github.com/ocaml/omd/issues/188)
- [Issue - Improve handling tricky edge cases](https://github.com/ocaml/omd/issues/184)
- [Issue - Support and test UTF-8](https://github.com/ocaml/omd/issues/182)
- [Issue - Add v2 PDF export via pandoc](https://github.com/realworldocaml/book/issues/3020)
