### ISSUE TITLE
PDF: improve listings style in the latex

### ISSUE THREAD

**Issue by avsm** [realworldocaml/book#3224]
Improve the listings styling with syntax highlighting etc in the LaTeX

**Comment by avsm** [comment]
@yminsky: 

> Might be nice to fix the overfull boxes (see page 22)
> Some of which can be done by widening the margins and adjusting the fonts.
> And maybe switching listings to a fixed-width font, so the width is more predictable.

**Comment by XVilka** [comment]
Unlike the OCaml manual using `minted` environment in case of RWO book might be more useful:
- https://www.overleaf.com/learn/latex/Code_Highlighting_with_minted
- https://tex.stackexchange.com/questions/389191/minted-vs-listings-pros-and-cons
