### ISSUE TITLE
Where is "Gérard Huet" in the History of ( ML -> Caml / OCaml )  ?!!

### ISSUE THREAD

**Issue by ahmadseleem** [realworldocaml/book#3225]
I found it very strange! that in the first edition of the book  and in the online draft of the second edition that you never mentioned:

### **Gérard Huet**
https://www.inria.fr/en/institute/inria-in-brief/prix-inria-par-annee/2011-prize-winners/grand-prize

- The person who: started the project: Caml in 1980.
- Robin Milner asked to him to change the name from ML to something else... 
You know the rest of the story...

The rest in the OCaml projects are all his students, aren't they ?!
Including :  Xavier Leroy.

So how come you never mentioned him ??!

![2019-11-27 17-51-57 1](https://user-images.githubusercontent.com/459241/69770853-6dbdf980-113f-11ea-87b3-7989dbdaad8e.png)

![2019-11-27 18-05-30 1](https://user-images.githubusercontent.com/459241/69771231-e5405880-1140-11ea-941c-8f3916e0ac74.png)

**Comment by avsm** [comment]
Thanks for the report; I'm reviewing this section later this week.
