### ISSUE TITLE
grep pattern in Single-File Programs chapter varies between machines

### ISSUE THREAD

**Issue by colinchan15** [realworldocaml/book#3226]
In the `Single-file programs` sub-chapter of the [`Files, Modules, and Programs`](http://dev.realworldocaml.org/files-modules-and-programs.html) chapter, there is a code block corresponding to building and running an executable into a single operation:
`grep -o '[[:alpha:]]*' freq.ml | dune exec ./freq.bc`. 

Although this `grep` pattern works on Linux machines, this is the result on a Mac: 
```
18:
  2: let
  2: open
```

Perhaps a note should be added that instead, this is the correct grep pattern to execute on a Mac to get the desired result that matches the text:
`grep -Eo '[[:alpha:]]+' freq.ml | dune exec ./freq.bc`

**Comment by yminsky** [comment]
Even better would be a command line that worked equally well on multiple unix flavors. If by chance you knew a good way of doing that, I'd be much obliged...

**Comment by colinchan15** [comment]
`grep -Eo '[[:alpha:]]+' freq.ml | dune exec ./freq.bc` also works on Linux machines (tested on the more popular distros: Fedora, Ubuntu, Arch). I assume that MacOS and Linux are the most used unix flavours for home users learning OCaml with RWOC.

**Comment by yminsky** [comment]
Awesome.  Would you be up for adding a PR with the change?

y

**Comment by colinchan15** [comment]
👍 Will do

**Comment by avsm** [comment]
Thanks Colin, now merged. We appreciate the contribution!
