### ISSUE TITLE
Upgrade examples to dune lang 2.x

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/book#3262]
The examples should reflect the most up-to-date tooling and since there are some significant changes between the 1.x and 2.x versions of the dune language, it's worth using 2.x to avoid to confuse users.

Note that this doesn't have to be done all at once and we can migrate example project per example project.

**Comment by NathanReb** [comment]
ATM it seems the only chapter that uses `(lang dune 1.x)` is the testing chapter. @yminsky would you accept a PR upgrading it to 2.x ?

**Comment by yminsky** [comment]
I would!

**Comment by avsm** [comment]
fixed in #3528
