### ISSUE TITLE
Semi-colons not apparent in generated PDF

### ISSUE THREAD

**Issue by brettgilio** [realworldocaml/book#3275]
Hi.

Compared to the generated HTML version of this book, the PDF version found at http://dev.realworldocaml.org/book.pdf lacks the `;;` terminating semi-colons for all examples where it is used with `utop`.

Just wanted to pass this along. Thanks!

**Comment by avsm** [comment]
Thanks; I can confirm the mystery of the missing semicolons in the PDF. I'll take a look.

**Comment by brettgilio** [comment]
Thanks :)
