### ISSUE TITLE
[Variables and Functions] Add description or class of operators in Precedence and Associativity table

### ISSUE THREAD

**Issue by shakthimaan** [realworldocaml/book#3277]
In the "Variables and Functions" chapter, in the Precedence and Associativity table, it will be good to also specify the class of operators like "arithmetic", "logical", "relational", "bitwise" etc. for easy remembrance? 

The other option is to add a column with a description, similar to https://en.cppreference.com/w/c/language/operator_precedence.

**Comment by yminsky** [comment]
I don't think this makes sense, since precedence is not tied to particular operators, but to whole classes, which don't share properties like "logical" or "arithmetic".
