### ISSUE TITLE
[Lists and Patterns] Add a note on "ignore" in Bench.Test.create

### ISSUE THREAD

**Issue by shakthimaan** [realworldocaml/book#3282]
In the `Performance` sub-section of `Limitations (and Blessings) of Pattern Matching` in the `Lists and Patterns` chapter, it will be good to write a sentence on what the "ignore" does in `Bench.Test.create` to give context.

At first glance, "ignore (plus_one_match 10)" looks like you are ignoring this particular test case, but, the benchmark reports the result for "plus_one_match."

It is not obvious for first time readers that you are actually wanting to ignore the return values for the specific test case.

**Comment by yminsky** [comment]
Good point!  Those ignores turn out to be unnecessary.  Removed in #3323
