### ISSUE TITLE
Use head and tail instead of hd and tl?

### ISSUE THREAD

**Issue by shakthimaan** [realworldocaml/book#3283]
In the "Lists and Patterns" chapter, is there any reason to use "hd" and "tl" instead of "head" and "tail". It is just two additional characters, but, is more explicit as shown below in the "Using Patterns to Extract Data from a List" section.
```
  # let rec sum l =
  #   match l with
  #   | [] -> 0
  #   | head :: tail -> head + sum tail
```

**Comment by avsm** [comment]
This is a very longstanding convention in ML-style languages. Primarily, the `List.hd` and `List.tl` functions exist, and so using these same names shows a correspondence via the pattern match.

**Comment by shakthimaan** [comment]
Thanks for the contextual information. This issue can be closed.
