### ISSUE TITLE
[Files, Modules and Programs] Mention OCaml programming style guidelines

### ISSUE THREAD

**Issue by shakthimaan** [realworldocaml/book#3286]
The "Concrete Types in Signatures" section in the `Files, Modules and Programs` chapter has the definition of `median`, which is a relatively large program compared to examples in prior chapters.

It will be good to mention about the OCaml programming style guidelines, for example, https://ocaml.org/learn/tutorials/guidelines.html.

The other alternative is to include the same as as Appendix.

**Comment by yminsky** [comment]
This doesn't feel like the right place to mention it, and I'm not sure it's the place I would point people anyway.
