### ISSUE TITLE
[Records] ::: {.allow_break data-type=note} in HTML output

### ISSUE THREAD

**Issue by shakthimaan** [realworldocaml/book#3290]
In the `Records` chapter, the format control text shows up in the HTML output. This is not the case with other chapters though. 
![records-output-error-shows-allow-break](https://user-images.githubusercontent.com/312622/78378998-5f9d4f80-75ef-11ea-88ce-b777bc5d2f4f.png)

**Comment by yminsky** [comment]
Should be fixed in 3324.  Thanks for pointing this out!
