### ISSUE TITLE
Error handling - backtraces has wrong name for function to get most recent backtrace

### ISSUE THREAD

**Issue by roddyyaga** [realworldocaml/book#3296]
The chapter on error handling says:

> You can also capture a backtrace within your program by calling Exn.backtrace, which returns the backtrace of the most recently thrown exception. This is useful for reporting detailed information on errors that did not cause your program to fail. 

but I believe that in the latest version of core the relevant function is `Backtrace.Exn.most_recent` not `Exn.backtrace` (per [here](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/Backtrace/Exn/index.html)).

**Comment by yminsky** [comment]
Good catch.  Fixed by #3327
