### ISSUE TITLE
Slight inconsistencies in the polymorphic variant examples in the Variants chapter

### ISSUE THREAD

**Issue by NathanReb** [realworldocaml/book#3306]
I found something disturbing while trying to enable automatic checking of the Variants chapter's examples in CI.

In this chapter there is an example that's meant to highlight some of the disadvantages of using polymorphic variants: https://github.com/realworldocaml/book/tree/master/book/variables-and-functions/examples.

This part of the chapter starts by showing an mli file and then goes on with a flawed implementation containing a typo in one of the constructor's name, claiming that it is correct because the compiler will infer a wider type for the function. This not true since the ml and the mli don't match.

Another example shortly following is meant to show that by annotating the function in the ml file we would then get an error.

I'm wondering if it would make sense to remove the mli file from the first, supposedly correct example and to use the mli to showcase the error rather than just the annotation although I do understand the value of showing type annotations can be used to debug such issues.

**Comment by NathanReb** [comment]
It is also worth noting that the first example and the second place the typo in different parts of the pattern matching!

See https://github.com/realworldocaml/book/blame/master/book/variants/README.md#L1114 and https://github.com/realworldocaml/book/blame/master/book/variants/README.md#L1135.

**Comment by yminsky** [comment]
I think this is fixed in #3328.  Or at least, the second problem with the annotations going in the wrong place seems fixed.  The first problem, I don't see, which is to say: the first example actually builds as I would expect.  Closing this, but it should rear its head if it's actually still a problem when you migrate this to the new workflow.
