### ISSUE TITLE
dune build 2.5 with variable %{os_type} error

### ISSUE THREAD

**Issue by ttuanho** [realworldocaml/book#3330]
Hi,

I'm trying dune-build the source code of the book and this error pops up:

```
$ make
File "duniverse/ctypes-foreign.0.17.1+dune/examples/fts/stub-generation/dune", line 3, characters 18-26:
3 |  (enabled_if (= %{os_type} "Unix"))
                      ^^^^^^^^
Error: This variable is only available since version 2.6 of the dune
language. Please update your dune-project file to have (lang dune 2.6).
make: *** [all] Error 1
```

But dune [v2.6 is not released yet](https://github.com/ocaml/dune/releases).
Am I missingsomething?

I'm on MacOS v10.15.4.

```
$ dune --version
2.5.1-166-gd29cb852
```

Thanks in advance.

**Comment by yminsky** [comment]
That's odd. I'm building on my box with Dune 2.5.0, and the build works fine for me.  @avsm any idea why this might be happening in ctypes?

**Comment by ttuanho** [comment]
> That's odd. I'm building on my box with Dune 2.5.0, and the build works fine for me. @avsm any idea why this might be happening in ctypes?

I don't think there's any problem with `ctypes` module tho. I tried modifying the dune setting and this error was still thrown in other modules.

I haven't figured the exact problem yet but downgrading Dune to v2.5.0 solves this issue tho. 
Thank you.

**Comment by samoht** [comment]
It's an issue with dune master, see https://github.com/ocaml/dune/issues/3494
