### ISSUE TITLE
filtered_bucket in add function is missing Boolean negation

### ISSUE THREAD

**Issue by anton-trunov** [realworldocaml/book#3332]
Please see this line in dictionary.ml (and the same snippet in the text): https://github.com/realworldocaml/book/blob/9d427dbce35e57c3ce044fed3836e3e275abae59/book/imperative-programming/examples/correct/dictionary/dictionary.ml#L47

The `remove` function below gets that right. Perhaps this indicates that `filtered_bucket` should be made a separate reusable helper function.

**Comment by yminsky** [comment]
Boy, that's embarrassing.  The referenced PR adds a test, and fixes the bug.

**Comment by anton-trunov** [comment]
Thank you!
