### ISSUE TITLE
Suggestion: Explanation of Matching Types for Records and Variants in Guided Tour

### ISSUE THREAD

**Issue by AndrewCarterUK** [realworldocaml/book#3343]
Referencing the [Records and Variants](https://github.com/realworldocaml/book/tree/7da963028f0c87518fcc199c656f6b54bc20bd5b/book/guided-tour#records-and-variants) section of the Guided Tour.

This example is given:

```ocaml env=main
# type point2d = { x : float; y : float }
type point2d = { x : float; y : float; }
```

And it is shown how it is demonstrated that OCaml can infer the type of `p` to be `point2d` in another example:

```ocaml env=main
# let p = { x = 3.; y = -4. }
val p : point2d = {x = 3.; y = -4.}
```

I'm not sure if other readers who are new to OCaml would agree with me, but I found this example raised an important question about the typing system that was not addressed. The question being, what happens when you have two differently named types with the same structure:

```ocaml env=main
# type point2d = { x : float; y : float }
type point2d = { x : float; y : float; }
```

```ocaml env=main
# type velocity2d = { x : float; y : float }
type velocity2d = { x : float; y : float; }
```

Then:

```ocaml env=main
# let p = { x = 3.; y = -4. }
val p : ? = {x = 3.; y = -4.}
```

It's easy enough to play around in the toplevel and see what actually happens. But it feels like a good opportunity to explain a bit more about structural typing and how OCaml handles types.

P.S. - Thanks very much for the work that everyone has put into this book. I'm working my way through it now and finding it very helpful.

**Comment by yminsky** [comment]
This seems like a subtlety that's better covered in the primary section on records, and there is some coverage there (see the section on reusing field names).  The guided tour is only intended to give the reader a taste of what's possible, not explain really how everything works.

Does the coverage in the Records chapter feel like it covers things well enough?

**Comment by AndrewCarterUK** [comment]
I think the coverage in the records chapter is very thorough.

This example just stood out to me as a bit of a contrast with the rest of the introduction, which dedicates a lot of time explaining how OCaml helps to eliminate bugs by being very specific.

I'm still new to OCaml, but it seems like a scenario where creating records in the way that is shown (without the module encapsulation) would potentially lead to problems. I'm not experienced enough to know if it would be considered bad practice?

As you said, the guided tour is an introduction and the topic is covered in more detail later. I just thought it worth raising as a discussion :)
