### ISSUE TITLE
v1 part of website has expired certificate

### ISSUE THREAD

**Issue by johnwhitington** [realworldocaml/book#3357]
(And when telling Safari to allow it, it redirects to realworldocaml.org:443 which goes nowhere)

**Comment by avsm** [comment]
Indeed; I'm actually pulling v1 off the Internet, as the content has well and truly expired.  The site will use the `realworldocaml.org/<version>/en` format from v2.0 onwards.

**Comment by yminsky** [comment]
Closing, since I think there's nothing left to do.
