### ISSUE TITLE
Forward reference phrased as if it was referring to already introduced material.

### ISSUE THREAD

**Issue by akoprow** [realworldocaml/book#3375]
In https://github.com/realworldocaml/book/blob/master/book/concurrent-programming/README.md#improving-the-echo-server:

> The command-line parsing for this program is based on the Command library that we introduced in Command Line Parsing{data-type=xref}.

With current setup that's actually the following chapter in the book.

**Comment by yminsky** [comment]
That's a fine point. I think it makes sense to just pull the command-line parsing chapter earlier. I'll give that a shot.

**Comment by yminsky** [comment]
Also, this example highlights that we're using the older style of Command use, which we should fix.

**Comment by yminsky** [comment]
Should be fixed now.
