### ISSUE TITLE
2 errors on running `make test`

### ISSUE THREAD

**Issue by idkjs** [realworldocaml/book#3418]
FYI. Not sure if this matter or not.

```sh
❯ make test                                                                              ─╯
dune runtest
File "duniverse/fmt/src/fmt.mli", line 27, characters 58-71:
Error: Unbound module Stdlib
File "duniverse/dune_/otherlibs/configurator/src/import.ml", line 105, characters 24-30:
Error: Unbound value of_seq
Done: 10757/18198 (jobs: 1)make: *** [test] Error 1

```

Thanks for all you do.

**Comment by emillon** [comment]
Hi! This project requires OCaml 4.10 at the moment:

https://github.com/realworldocaml/book/blob/12fe72c037f34e4eb6d4dbb82ed8e4badacbf27b/rwo.opam#L14

Based on the error message, it seems that you're using an older version of OCaml. If you run this in a 4.10.1 switch this should work.

**Comment by idkjs** [comment]
Thanks. I guess `Stdlib` is not available on older versions, maybe was `Pervasives`? And that is what is telling you that? 

Thank again

**Comment by emillon** [comment]
Yes, in 4.07 all toplevel modules were moved under a new open-by-default `Stdlib` module.
