### ISSUE TITLE
new chapters to consider for v2

### ISSUE THREAD

**Issue by avsm** [realworldocaml/book#3437]
From https://twitter.com/avsm/status/1316324769718063104

summary is: (to edit)

- Building (dune)
- packaging and distributing code (OPAM)
- dealing with complex projects with a mix of C, Rust and JavaScript
- expect tests
- fuzzing (crowbar)
- documentation (odoc)
- debugging (ocamldebug, rr)
- performance debugging (ctf, perf, memtrace)
- Structuring OCaml codebases eg how to design with modules. Without adding 1000 pages to the book I’d like to have a Advanced Real World OCaml book that pushes on property testing, GADTs and other clever language features
- Maybe a chapter on incremental?
- Tips for structuring very large OCaml projects
- Dune would be really cool
- I'd love to see a bit around structuring larger projects with tooling that's come along since the last revision - Dune, in particular, but I'm sure there are others...
- An introduction to monads, e.g.,  lwt, and the new operators let+, let* and applicative functors.
- There is a chapter about parsing, but almost nothing on pretty-printing.
- JSOO, consuming databases in OCaml 
- A little more information about PPX please
- UTF-8 string processing!
- Antipatterns chapter or index entry.

**Comment by ejmg** [comment]
all of them sound great, but extra :+1: for UTF-8 string processing, PPX, and intro to monads/`let+`/`let*`/applicative functors :slightly_smiling_face:

**Comment by benjub** [comment]
IMHO tooling, testing, debugging and guidelines/best practices for large projects would be a valuable addition to the existing OCaml literature and would justify the "real world" of the title.

**Comment by yminsky** [comment]
Well, there's a draft of the testing chapter up now...

https://dev.realworldocaml.org/testing.html

**Comment by yminsky** [comment]
The v2 chapters have been finalized, so closing this issue.
