### ISSUE TITLE
weird type inference for `find_mismatches` in chapter 7

### ISSUE THREAD

**Issue by ejmg** [realworldocaml/book#3444]
## issue

second example function of chapter 7 (error handling), we are provided the function `find_mismatches` with inferred type signature from utop:
```ocaml
let find_mismatches table1 table2 =
  Hashtbl.fold table1 ~init:[] ~f:(fun ~key ~data mismatches ->
    match Hashtbl.find table2 key with
    | Some data' when data' <> data -> key :: mismatches
    | _ -> mismatches
  )
;;
val find_mismatches :
  ('a, int) Hashtbl.Poly.t -> ('a, int) Hashtbl.Poly.t -> 'a list = <fun>
```
when ran locally, however, i get something much more specific for the inferred type:
```ocaml
val find_mismatches :
  ('a, int) Timezone.Table.hashtbl ->
  ('a, int) Timezone.Table.hashtbl -> 'a list = <fun>
```
## config 
i've made sure to `open Base` for the utop session and have my `.ocamlinit` setup as suggested by the website current, eg:

```
#use "topfind";;
#thread;;
#require "core.top";;
```
## possible solution
i discovered that if i removed the directive `#require "core.top"` from my utop config and manually run `#require "base"`, i get something that seems (relatively) more correct:
```ocaml
─( 18:10:30 )─< command 0 >───────────────────────────────────────────────────────────────{ counter: 0 }─
utop # #require "base" ;;
─( 18:10:30 )─< command 1 >───────────────────────────────────────────────────────────────{ counter: 0 }─
utop #
open Base
let find_mismatches table1 table2 =
  Hashtbl.fold table1 ~init:[] ~f:(fun ~key ~data mismatches ->
    match Hashtbl.find table2 key with
    | Some data' when data' <> data -> key :: mismatches
    | _ -> mismatches
  )
;;
val find_mismatches :
  ('a, int) Base.Hashtbl.t -> ('a, int) Base.Hashtbl.t -> 'a list = <fun>
```

not sure if this is really an issue as it is something to do with my local setup pushing OCaml to infer a tighter type constraint on the function so apologies if this is just noise on my part.

**Comment by yminsky** [comment]
This is bad behavior from OCaml in terms of how it picks type aliases, which is unpredictable, and depends on what is currently in your type environment. Hashtbl.Poly.t and Base.Hashtbl.t are the same type. This should get fixed down the line when some better heuristics for picking types to display is upstreamed in to the compiler.
