### ISSUE TITLE
[precedence and associativity][request] list (converted from table) is not clear

### ISSUE THREAD

**Issue by rprimus** [realworldocaml/book#3445]
Tue 20 Jul 2021 09:17:20 BST

The new precedence `list` presents as very confusing compared with the previous (RWO) table or the (ocaml.org) table for two reasons:
1.  Separation with `|` character between operators and precedence level
2.  Separation of operators using `,` vs ` `   (difficult to distinguish between adjoining `.` and `,`

 For this, can an image be used in its place?

Current pdf: page 39 [list] - using comma:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/278414/126286943-0ca782d5-1ab0-4d11-826b-dc514e677adf.png">

Previous pdf: page 39 [table] - using comma:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/278414/126288228-e27084b0-5c8d-4107-a8a1-235e4962eb9d.png">

https://ocaml.org/releases/4.12/ocaml-4.12-refman.pdf [table] - using space:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/278414/126289538-15b5b8bb-237b-401b-9175-4189cd00fbd9.png">

https://ocaml.org/api/Ocaml_operators.html [table] - using space:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/278414/126287137-f0d43846-d67d-49f9-86cd-60788b67eb5e.png">

### Note:
All the above images were clipped using their natural sizes/appearance.  The `pdf` images were clipped from `Preview` and the `html` page from `Firefox`.   Not trying to subconsciously influence by using a `bigger` image.

**Comment by avsm** [comment]
This is the result of an incomplete edit while porting the PDF styles. Thanks for spotting this!

**Comment by yminsky** [comment]
@avsm Any progress on fixing this one?
