### ISSUE TITLE
Typo in Imperative Programming

### ISSUE THREAD

**Issue by benjub** [realworldocaml/book#3464]
Unless I'm mistaken, in https://dev.realworldocaml.org/imperative-programming.html,
> of type s Lazy.t

should be
> of type s lazy_t

Also, in https://dev.realworldocaml.org/variables-and-functions.html,
> two arguments. a function

should be
> two arguments, a function

**Comment by avsm** [comment]
fixed latter; 30d1ea9ac4646df580f9250ad10d8f944019719b
