### ISSUE TITLE
Maybe an easier way to use menhir with dune in Chanpter "Parsing with OCamllex and Menhir"

### ISSUE THREAD

**Issue by Loutine** [realworldocaml/book#3469]
Thanks for the great work of the writer to introduce menhir this amazing tools, by reading the relevant chapter I found it's quite confusing to use dune like this
``` dune
(rule
 (targets short_parser.mli short_parser.ml)
  (deps   short_parser.mly)
  (action (ignore-stderr (run menhir --external-tokens Json --explain ${<}))))
```
and used this script can't compile the project,after editing the variable alias in "action" term it finally worked
``` dune
(rule
 (targets short_parser.mli short_parser.ml)
  (deps   short_parser.mly)
  (action (ignore-stderr (run menhir --external-tokens Json --explain ${deps}))))
```
and reading the documentation of dune I found a (maybe?) better way to use menhir with dune
```dune
(menhir
 (modules short_parser)
 (flags --external-tokens Json --explain)
 (infer false)
)
```
just a little advice if i did something wrong please tell me, I'm still a beginner to OCaml  
and sorry for my poor English......

**Comment by avsm** [comment]
Thanks for taking the trouble to create this issue and spotting this. The `(menhir)` rule was added after that chapter was written, so your suggestion is definitely an improvement. I'll make that change when editing that chapter next week...

**Comment by avsm** [comment]
All fixed now; the chapter uses `(menhir)`. Thanks for the suggestion!
