### ISSUE TITLE
"Variance Annotations" note overflows page in PDF

### ISSUE THREAD

**Issue by kerrickstaley** [realworldocaml/book#3471]
# Summary
The note (green background) discussing Variance Annotations is very long. When I generate the PDF on my set-up, this note flows into the bottom margin of the page that it's on. Here's what it looks like for me:

<img src="https://user-images.githubusercontent.com/184773/135202400-b4fc6c16-7b5e-48fc-8a8f-f57ad16f280c.png" width="400">

# System configuration
- Arch Linux, updated in the past week-ish
- book repo commit 802bcfcf92f2160e2d07bdcb97149e360da4c8a6 (latest as-of when I'm writing this)

# Steps to reproduce
```
sudo pacman -S opam dune pandoc
make
dune build @pdf-wip
```

**Comment by yminsky** [comment]
That's a good catch. @avsm any thoughts on this?

**Comment by yminsky** [comment]
After talking a bit with Anil off-line, I think we'll fix this by adjusting the text to integrate this rather long note in to the text. Thanks for the heads-up!
