### ISSUE TITLE
Minor contradiction after removing references to core_kernel

### ISSUE THREAD

**Issue by prekel** [realworldocaml/book#3516]
https://github.com/realworldocaml/book/blob/2eec2c8faebf7b4f0c0119d3b64ce72bf24877e7/book/prologue/README.md?plain=1#L245-L251 (introduced in #3454)

> `Core` currently requires a UNIX based operating system
> `Core` is an extension of `Base` which works anywhere OCaml does, and in particular works on Windows

Isn't this contradictory? I think is better to write something like " `Core` earlier requires a UNIX based operating system"

**Comment by yminsky** [comment]
The wording is confusing here.
