### ISSUE TITLE
Typo in Files, Modules, and Programs

### ISSUE THREAD

**Issue by benjub** [realworldocaml/book#3519]
On https://dev.realworldocaml.org/files-modules-and-programs.html, instead of
>And if we then put open Common after open Base

you probaly meant
>And if we then put open Option after open Base

**Comment by yminsky** [comment]
Oh, yeah, this is super confusing.  open Common is what was intended, but the text is super confusing, and the filename in question is never surfaced to the user. I'll fix this in #3521.
