### ISSUE TITLE
The chapter on error handling should cover case-analysis of Error.t

### ISSUE THREAD

**Issue by hexagonrecursion** [realworldocaml/book#3526]
Sometimes it is not enough to know whether a given operation failed or not. Sometimes the code needs to know why it failed to decide how to proceed. Most commonly the code needs to distinguish between a number of different predefined error kinds/reasons. The chapter on error handling covers how to catch a specific kind of exception, but it does not provide the same information for `Error.t`. I assume you have simply overlooked this.

**Comment by yminsky** [comment]
Not an oversight, and this kind of code is mostly (but not entirely) viewed as bad practice. Indeed, there's a whole section aimed at discouraging this kind of code, called "catching specific exceptions".
