### ISSUE TITLE
Code example in "Lists and patterns"

### ISSUE THREAD

**Issue by benjub** [realworldocaml/book#3574]
In https://dev.realworldocaml.org/lists-and-patterns.html, for the table rendering example, the following two functions are defined:
```
let pad s length =
  " " ^ s ^ String.make (length - String.length s + 1) ' ';;

let render_row row widths =
  let padded = List.map2_exn row widths ~f:pad in
  "|" ^ String.concat ~sep:"|" padded ^ "|";;
```
It looks like one concatenation (and one addition) per table cell would be saved with the shorter code:
```
let pad s length =
  s ^ String.make (length - String.length s) ' ';;

let render_row row widths =
  let padded = List.map2_exn row widths ~f:pad in
  "| " ^ String.concat ~sep:" | " padded ^ " |";;
```

**Edit**: the same thing can be done in the definition of `render_separator`.

**Comment by yminsky** [comment]
That looks nice! I hope to get to this, but if you happen to have time to make a PR with the changes, that will make it more likely I get the fix in!

**Comment by yminsky** [comment]
This looks all taken care of. Thanks for the PR!
