### ISSUE TITLE
Small inconsistency in the text

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [realworldocaml/book#3629]
In Chapter 3 in section [Terser and Faster Patterns](https://dev.realworldocaml.org/lists-and-patterns.html#terser-and-faster-patterns) you write: "While we’re at it, we’ll use the `function` keyword to eliminate the need for an explicit `match:`", however next three code example does not do it and continue to use `match`.

**Comment by yminsky** [comment]
Good catch. Thanks!
