### ISSUE TITLE
[SUGGESTION] Upload PDF and EPUB builds as releases

### ISSUE THREAD

**Issue by davisuga** [realworldocaml/book#3632]
It would make it easier for people who just want to download and read it offline.

**Comment by avsm** [comment]
We'll have to provide PDFs and EPUB builds via our publisher, not through this build. But it'll all still be open access and free!

**Comment by andreystepanov** [comment]
@avsm Where exactly `epub` format can be downloaded?

Having hard time finding it on `cambridge.org` website. 
Only PDF available, which is not the best friend of Kindle :)
