### ISSUE TITLE
Where to buy this book?

### ISSUE THREAD

**Issue by mimoo** [realworldocaml/book#3645]
Hello,

It looks like the 2nd revision was released, but I cannot find the print book online, am I missing something?

**Comment by avsm** [comment]
It'll be in print later this year; around October or so.

**Comment by mimoo** [comment]
cool! maybe a good idea to remove this from the website :D 

<img width="263" alt="Screen Shot 2022-08-15 at 4 57 09 PM" src="https://user-images.githubusercontent.com/1316043/184659633-862e93f0-dbfa-4601-bd29-2834a3dc892d.png">

**Comment by avsm** [comment]
indeed! I'm refreshing the website now; thanks for the reminder :-)
